Feature/architecture
st235/Catovasia pull request #3
Opened 2018-05-21 06:51 UTC by Chog0

2018-05-21 08:07 UTC, st235 requested changes

2018-05-21 08:07 UTC, st235 commented on app/build.gradle
> +    implementation 'com.android.support:support-v4:27.1.1'
libs.support

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/NetRepository.java
> +
redundant diff

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/NetRepository.java
> +        MutableLiveData<Result<List<Picture>>> liveData = new MutableLiveData<>();
`new MutableLiveData<>()` every time you call method

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/NetRepository.java
> +        unsplashApiClient.getCatsPhotos(page).enqueue(new Callback<PictureResponse>() {
about cancel requests.
is it `live data` duty now?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/Item.java
> +
redundant

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +    // TODO: Rename parameter arguments, choose names that match
`// TODO(chog0)`
empty todos are dangerous.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +
redundant

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +    // TODO: Rename and change types of parameters
`TODO(chog0)`

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +        // Required empty public constructor
it is created by default, therefore it is called default.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +    public static SavedCatsFragment newInstance(String param1, String param2) {
?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +    // TODO: Rename and change types and number of parameters
`//TODO(chog0)`

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +
redundant

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +
redundant

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SavedCatsFragment.java
> +}
why we need this fragment?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/SettingsFragment.java
> +public class SettingsFragment extends Fragment {
Looks like copy paste

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/FeedViewModel.java
> +    private NetRepository repository;
`final`?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/FeedViewModel.java
> +
red.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/FeedViewModel.java
> +    public LiveData<Result<List<Picture>>> getFeedLiveData(int page){
`@NonNull`?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/FeedViewModel.java
> +    public FeedViewModel(NetRepository repository) {
`@NonNull`?

2018-05-21 08:07 UTC, st235 commented on app/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +                <feedItem
???

2018-05-21 08:07 UTC, st235 commented on app/src/main/res/drawable-v24/ic_launcher_foreground.xml
> +                <feedItem
???

2018-05-21 08:07 UTC, st235 commented on app/src/main/res/layout/feed_item.xml
> +</android.support.constraint.ConstraintLayout>
no eof

2018-05-21 08:07 UTC, st235 commented on app/src/main/res/layout/fragment_editor.xml
> +    <!-- TODO: Update blank fragment layout -->
`//TODO(chog0)`

2018-05-21 08:07 UTC, st235 commented on app/src/main/res/values/styles.xml
> +        <feedItem name="colorPrimary">@color/colorPrimary</feedItem>
auto refactoring mistake

2018-05-21 08:07 UTC, st235 commented on deps.gradle
> +
red.

2018-05-21 08:07 UTC, st235 commented on deps.gradle
> +
red.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/PictureViewModel.java
> +    public void select(Item item){
`@NonNull`

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/viewmodels/PictureViewModel.java
> +    public LiveData<Item> getSelectedItem() {
`@NonNull`

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    private String catName;
where is the setters to this fields?

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    private String pictureDominantColor;
N here and upper

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    public String getCatName() {
`@NonNull`

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    public String getPictureDominantColor() {
N

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    public String getFullPicture() {
N

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +    public String getThumbPicture() {
N

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +
red.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/FeedItem.java
> +
red.

2018-05-21 08:07 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/net/Result.java
> +    @NonNull private final Status status;
```
@NonNull
private final Status status;
```

Insert new line please

2018-05-21 20:29 UTC, Chog0 commented on app/src/main/res/layout/feed_item.xml
> +</android.support.constraint.ConstraintLayout>
?

2018-05-21 20:43 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/Item.java
> +public abstract class Item {
why u use `abstract class` but not `interface`?

2018-05-21 20:43 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/ui/Item.java
> +    public abstract int getViewType();
`getViewType`?

2018-05-21 21:11 UTC, st235 commented on app/src/main/res/layout/feed_item.xml
> +</android.support.constraint.ConstraintLayout>
new line at eof 😅

2018-05-22 21:01 UTC, st235 reviewed
Last changes 😅

2018-05-22 21:01 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/NetRepository.java
> +    private MutableLiveData<Result<List<Picture>>> liveData = new MutableLiveData<>();
`final`

2018-05-22 21:01 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/net/Result.java
> +    public static<T> Result<T> success(@NonNull T data){
methods names should contains a verb
`create` for example

2018-05-22 21:01 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/net/Result.java
> +    public static <T> Result<T> failure(String message, @Nullable T data){
create

2018-05-22 21:01 UTC, st235 commented on app/src/main/java/st235/github/com/catovasia/data/net/Result.java
> +    public static <T> Result<T> failure(String message, @Nullable T data){
`@NonNull` message

2018-05-23 21:07 UTC, st235 approved these changes
👍🏿

2018-05-23 21:07 UTC, merged